- name: Condition in ansible
  hosts: local
  connection: local
  vars:
    Name: Hotstar
    IS_LIVE: true
  tasks:
  - name: checking is live or not
    ansible.builtin.debug:
      msg: "{{ Name }} yes it is live"
    when: IS_LIVE