- name: gathering facts
  hosts: local
  connection: local
  tasks:
  # - name: print facts
  #   ansible.builtin.debug:
  #     msg: "{{ ansible_facts }}"
    
  - name: print os family
    ansible.builtin.debug:
      msg: "yes os family is RedHat"
    when: ansible_facts.os_family ==  "RedHat"
  - name: print package manager
    ansible.builtin.debug:
      msg: "Yes package manager is debian"
    when: ansible.facts.family == "Ubuntu"