- name: Installing nginx and java
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install both packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - java
